version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: banco_admin
      POSTGRES_PASSWORD: 23456
      POSTGRES_DB: conta_bancaria_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: wallace89.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
